# get the hostname from all the hosts, use groups to filter out the masters and workers if not provisioned yet
---
- name: Get Hostnames
  hosts: hypervisor

  tasks:
  - name: Get Hostname
    ansible.builtin.command: hostname
    register: hostname
    changed_when: false
  - name: Echo Hostname
    ansible.builtin.debug:
      msg: "{{ hostname.stdout }}"
